included_scenario_yaml: "ws02/src/pt_potential_controller/config/scenarios/comp_base.yaml"

anchors:
  pose:
    id: "perceptron"
    pos_topic: "/pt_pose"

  point:
    id: "enemy"
    pos_topic: "/enemy_pose"
    potentials:
      constant: # slowly approach at a distance
        const: -1.25 # -0.75
      linear: # speed up when close
        lin: -0.5
        f_max: 3.0
        d_off: 0.25 # try to keep some distance between bot centers to avoid getting stuck on enemy
