included_scenario_yaml: "ws02/src/pt_potential_controller/config/scenarios/empty_arena.yaml"

anchors:
  pose:
    id: "perceptron"
    pos_topic: "/pt_pose"

  point:
    id: "enemy"
    pos_topic: "/enemy_pose"
    potentials:
      constant: # slowly approach at a distance
        const: -0.25
      linear: # speed up when close
        lin: -0.5

  line:
    id: "enemy_trajectory"
    pos_topic: "/enemy_trajectory"
    potentials:
      exponential:
        base: 2.718281828
        exp: 0.2
      constant: # counter min. force of 1 due to exponential function
        const: -1.0