included_scenario_yaml: "ws02/src/pt_potential_controller/config/scenarios/comp_base.yaml"

anchors:
  point:
    id: "enemy"
    pos_topic: "/enemy_pose"
    potentials:
      linear:
        lin: -0.75
        f_max: 2.0
        d_offset: 0.75
        d_invert: false
      linear:
        lin: 0.30
        angle_twist: 1.57
        f_max: 0.60
        f_sign_override: 1 # -1 ... always attract, 1 ... always repell
        d_offset: 0.75
