anchors:
  line:
    id: "wall_left"
    pos_x0: -0.75
    pos_y0:  0.75
    pos_x1: -0.75
    pos_y1: -0.75
    potentials:
      exponential:
        base: 2.718281828
        exp: 0.01

  line:
    id: "wall_right"
    pos_x0:  0.75
    pos_y0:  0.75
    pos_x1:  0.75
    pos_y1: -0.75
    potentials:
      exponential:
        base: 2.718281828
        exp: 0.01

  line:
    id: "wall_bottom"
    pos_x0: -0.75
    pos_y0: -0.75
    pos_x1:  0.75
    pos_y1: -0.75
    potentials:
      exponential:
        base: 2.718281828
        exp: 0.01

  line:
    id: "wall_top"
    pos_x0: -0.75
    pos_y0:  0.75
    pos_x1:  0.75
    pos_y1:  0.75
    potentials:
      exponential:
        base: 2.718281828
        exp: 0.01

  point:
    id: "hazard_blue"
    pos_x: -0.575
    pos_y: -0.575
    potentials:
      exponential:
        base: 2.718281828
        exp: 0.001
        f_max: 2.0
      constant:
        const: -1.0

  point:
    id: "hazard_red"
    pos_x: 0.575
    pos_y: 0.575
    potentials:
      exponential:
        base: 2.718281828
        exp: 0.001
        f_max: 2.0
      constant:
        const: -1.0

  point:
    id: "hazard_a"
    pos_x: -0.18
    pos_y:  0.18
    potentials:
      exponential:
        base: 2.718281828
        exp: 0.001
        f_max: 2.0
      constant:
        const: -1.0

  point:
    id: "hazard_b"
    pos_x:  0.18
    pos_y: -0.18
    potentials:
      exponential:
        base: 2.718281828
        exp: 0.001
        f_max: 2.0
      constant:
        const: -1.0


visualization:
  scale: 0.005 # world coordinate units per pixel
  width: 400  # window size in pixels
  height: 400
  center_x: 0.0 # center of window in world coordinates
  center_y: 0.0
  show_forces: false
  f_max: 10.0 # max. force to scale colors for
