anchors:
  pose:
    id: "perceptron"
    pos_x: -1.0
    pos_y: 0.0
    pos_t: 0.0
    pos_topic: "/own_pose"

  point:
    id: "enemy"
    pos_x: 1.0
    pos_y: 0.0
    pos_topic: "/enemy_pose"
    potentials:
      constant: # f = const
        const: -1.5

  point:
    id: "obstacle"
    enabled: false
    pos_x: 0.0
    pos_y: 1.0
    potentials:
      exponential: # f = base^(exp*d)
        base: 2.718281828
        exp: 0.1
        f_max: 10.0 # maximum repulsion higher than opponents attraction!

  line:
    id: "wall_left"
    pos_x0: -3.0
    pos_y0: -2.0
    pos_x1: -3.0
    pos_y1: 2.0
    potentials:
      exponential:
        base: 2.718281828
        exp: 0.1

  line:
    id: "wall_right"
    pos_x0: 3.0
    pos_y0: -2.0
    pos_x1: 3.0
    pos_y1: 2.0
    potentials:
      exponential:
        base: 2.718281828
        exp: 0.1

  line:
    id: "wall_bottom"
    pos_x0: -3.0
    pos_y0: -2.0
    pos_x1: 3.0
    pos_y1: -2.0
    potentials:
      exponential:
        base: 2.718281828
        exp: 0.1

  line:
    id: "wall_top"
    pos_x0: -3.0
    pos_y0: 2.0
    pos_x1: 3.0
    pos_y1: 2.0
    potentials:
      exponential:
        base: 2.718281828
        exp: 0.1


visualization:
  scale: 0.01 # world coordinate units per pixel
  width: 640  # window size in pixels
  height: 480
  center_x: 0.0 # center of window in world coordinates
  center_y: 0.0
  f_max: 10.0 # max. force to scale colors for
