included_scenario_yaml: "ws02/src/pt_potential_controller/config/scenarios/empty_arena.yaml"

anchors:
  pose:
    id: "perceptron"
    pos_topic: "/pt_pose"

  point:
    pos_x: -0.6
    pos_y: -0.6
    id: "destination"
    pos_topic: "/destination_pose"
    potentials:
      constant: # approach destination
        const: -0.1
      linear: # stop when close
        lin: 0.01
        f_max: 0.1

  point:
    id: "rotation_center"
    pos_x: 0.0
    pos_y_: 0.0