included_scenario_yaml: "ws02/src/pt_potential_controller/config/scenarios/comp_base.yaml"

anchors:
  point:
    id: "enemy"
    pos_topic: "/enemy_pose"
    potentials:
      constant: # approach enemy ...
        const: -0.5
      linear: # ... while strafing sideways
        lin: 0.30
        angle_twist: -1.57
        f_max: 0.60
        f_sign_override: 1 # -1 ... always attract, 1 ... always repell
        d_invert: false # need more speed at longer distances to get consistent circling rate
