/**:
  ros__parameters:
    scenario_path: "ws02/src/pt_potential_controller/config/scenarios/competition_circle_cw.yaml"
    controlled_anchor: "perceptron"
    rotation_target_anchor: "enemy"
    frequency: 30.0
    w_pid_p: 0.75
    w_pid_i: 0.0
    w_pid_d: 5.0
    w_pid_min: 0.000
    vis_enabled: True
    ctrl_enabled: False