anchors:
  anchor:
    id: "perceptron"
    type: "pose"
    position:
      type: "pose_topic"
      topic_name: "/own_pose"
    feedback:
      type: "cmd_vel_topic"
      topic_name: "/cmd_vel"
      frequency: 10.0
      max_vel_x: 5.0
      max_vel_y: 5.0
      max_vel_w: 5.0
      rotation_target: "enemy"
      w_pid_p: 1.0
      w_pid_i: 1.0
      w_pid_d: 1.0

  anchor:
    id: "enemy"
    type: "point"
    position:
      type: "pose_topic"
      topic_name: "/enemy_pose"
    potentials:
      constant: # f = const
        const: 0.5
      linear: # f = lin*d
        lin: 1.0
      exponential: # f = base^(exp*d)
        base: 2.718281828
        exp: 1.0
        d_rec: true # take reciprocal of distance before calculating f
        f_max: 10.0 # limit maximum force

  anchor:
    id: "obstacle"
    type: "point"
    position:
      type: "static_point"
      x: 0.0
      y: 1.0
    potentials:
      exponential:
        sign_override: "repell" # f always applied as repelling force
        base: 2.718281828
        exp: 1.0
        d_rec: true
        f_max: 50.0 # maximum repulsion higher than opponents attraction!

  visualization:
    scale: 0.01 # world coordinate units per pixel
    width: 640  # window size in pixels
    height: 480
    center_x: 0.0 # center of window in world coordinates
    center_y: 0.0
    f_max: 10.0 # max. force to scale colors for
